name: measure_size
description: A widget that provides a callback that is triggered when its size changes
homepage: https://github.com/mhrst/measure_size
repository: https://github.com/mhrst/measure_size
issue_tracker: https://github.com/mhrst/measure_size/issues
version: 3.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^2.0.0
  flutter_test:
    sdk: flutter
